class FaqPageLocators:

    def __init__(self, page):
        self.questions_box = page.locator("//div[@class='question-collapse']")
        self.main_title = page.locator("//div[@class='pricing-main-title']")
        self.first_question = page.locator("(//div[@class='question-collapse']/div)[1]")
        self.second_question = page.locator("(//div[@class='question-collapse']/div)[2]")
        self.third_question = page.locator("(//div[@class='question-collapse']/div)[3]")
        self.fourth_question = page.locator("(//div[@class='question-collapse']/div)[4]")
        self.fifth_question = page.locator("(//div[@class='question-collapse']/div)[5]")
        self.sixth_question = page.locator("(//div[@class='question-collapse']/div)[6]")
        self.seventh_question = page.locator("(//div[@class='question-collapse']/div)[7]")
        self.first_question_title = page.locator("(//div[@class='question-collapse']/div)[1]/div[@class='collapse-box-df-title']/div/p")
        self.first_question_description = page.locator("(//div[@class='question-collapse']/div)[1]/div[@class='open-tab-desc']/p")
        self.second_question_title = page.locator("(//div[@class='question-collapse']/div)[2]/div[@class='collapse-box-df-title']/div/p")
        self.second_question_description = page.locator("(//div[@class='question-collapse']/div)[2]/div[@class='open-tab-desc']/p")
        self.third_question_title = page.locator("(//div[@class='question-collapse']/div)[3]/div[@class='collapse-box-df-title']/div/p")
        self.third_question_description = page.locator("(//div[@class='question-collapse']/div)[3]/div[@class='open-tab-desc']/p")
        self.fourth_question_title = page.locator("(//div[@class='question-collapse']/div)[4]/div[@class='collapse-box-df-title']/div/p")
        self.fourth_question_description = page.locator("(//div[@class='question-collapse']/div)[4]/div[@class='open-tab-desc']/p")
        self.fifth_question_title = page.locator("(//div[@class='question-collapse']/div)[5]/div[@class='collapse-box-df-title']/div/p")
        self.fifth_question_description = page.locator("(//div[@class='question-collapse']/div)[5]/div[@class='open-tab-desc']/p")
        self.sixth_question_title = page.locator("(//div[@class='question-collapse']/div)[6]/div[@class='collapse-box-df-title']/div/p")
        self.sixth_question_description = page.locator("(//div[@class='question-collapse']/div)[6]/div[@class='open-tab-desc']/p")
        self.seventh_question_title = page.locator("(//div[@class='question-collapse']/div)[7]/div[@class='collapse-box-df-title']/div/p")
        self.seventh_question_description = page.locator("(//div[@class='question-collapse']/div)[7]/div[@class='open-tab-desc']/p")